// Builds TEST-MATRIX.md from Playwright's JSON report (test-results/results.json).
// Usage: node scripts/test-report.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import os from 'node:os'

const report = JSON.parse(readFileSync('test-results/results.json', 'utf8'))

const MODES = ['naive', 'query', 'virtual']
const MODE_LABEL = { naive: 'Without TanStack Query', query: 'TanStack Query', virtual: 'TanStack Query + Virtual' }
const ICON = { passed: '✅', failed: '❌', timedOut: '⏱️', skipped: '⏭️', interrupted: '⛔' }

// ---- Flatten every test with its describe path, status, duration, annotations.
const tests = []
function walk(suite, path) {
  for (const spec of suite.specs ?? []) {
    for (const t of spec.tests) {
      const r = t.results.at(-1) ?? {}
      const annotations = [...(t.annotations ?? []), ...(r.annotations ?? [])]
      const ann = {}
      for (const a of annotations) ann[a.type] = a.description
      tests.push({
        file: spec.file,
        group: path.filter(Boolean).join(' › '),
        title: spec.title,
        status: r.status ?? 'skipped',
        duration: r.duration ?? 0,
        error: r.error?.message ?? r.errors?.[0]?.message,
        ann,
      })
    }
  }
  for (const s of suite.suites ?? []) walk(s, [...path, s.file === s.title ? '' : s.title])
}
for (const s of report.suites) walk(s, [])

const secs = (ms) => `${(ms / 1000).toFixed(1)} s`
const fmtMs = (ms) => (ms == null ? '–' : ms >= 1000 ? `${(ms / 1000).toFixed(1)} s` : `${ms} ms`)
const fmtInt = (n) => (n == null ? '–' : n.toLocaleString('en-US'))
const strip = (s) => (s ?? '').replace(/\u001b\[[0-9;]*m/g, '')

const count = (st) => tests.filter((t) => t.status === st).length
const passed = count('passed')
const failed = tests.length - passed - count('skipped')
const browser = tests.find((t) => t.ann.browser)?.ann.browser ?? 'Chrome (version not recorded)'

const out = []
const line = (s = '') => out.push(s)

line('# Test matrix: WebOpt Lab')
line()
line(`Generated by \`npm run test:report\` from the Playwright run on ${new Date(report.stats.startTime).toLocaleString('en-GB')}.`)
line()
line('| | |')
line('|---|---|')
line(`| **Result** | ${failed === 0 ? '✅ all passing' : `❌ ${failed} failing`} |`)
line(`| Tests | ${tests.length} total · ${passed} passed · ${failed} failed · ${count('skipped')} skipped |`)
line(`| Run time | ${secs(report.stats.duration)} |`)
line(`| Browser | ${browser}, headless, 1400×1000 viewport |`)
line(`| Machine | ${os.cpus()[0]?.model.trim()} · ${Math.round(os.totalmem() / 1e9)} GB RAM · ${os.type()} ${os.release()} |`)
line(`| Build | production (\`vite build\` + \`vite preview\`), one worker |`)
line()
line('Legend: ✅ passed · ❌ failed · ⏱️ timed out · ⏭️ skipped · — not run for this tab')
line()

// ---- 1. Feature × tab matrix
const feature = tests.filter((t) => t.group === 'Feature matrix')
if (feature.length) {
  line('## 1. Feature × tab matrix')
  line()
  line('Every feature runs against each of the three list tabs with 10,000 rows. Numbers in a cell are what that test measured.')
  line()
  const features = [...new Set(feature.map((t) => t.title.replace(/ \[\w+\]$/, '')))]
  line(`| Feature | ${MODES.map((m) => MODE_LABEL[m]).join(' | ')} |`)
  line(`|---|${MODES.map(() => ':-:').join('|')}|`)
  for (const f of features) {
    const cells = MODES.map((m) => {
      const t = feature.find((x) => x.title === `${f} [${m}]`)
      if (!t) return '—'
      const extra = t.ann.domNodes
        ? ` ${fmtInt(Number(t.ann.domNodes))} nodes`
        : t.ann.clickPaintMs
          ? ` ${fmtMs(Number(t.ann.clickPaintMs))}`
          : t.ann.idleFps
            ? ` ${t.ann.idleFps} fps`
            : ''
      return `${ICON[t.status] ?? t.status}${extra}`
    })
    line(`| ${f} | ${cells.join(' | ')} |`)
  }
  line()
}

// ---- 2. Performance matrix
const perf = tests.filter((t) => t.ann.perf).map((t) => ({ ...JSON.parse(t.ann.perf), status: t.status }))
// Cells that never produced numbers (e.g. timed out) still get a slot in every table.
const perfFailed = tests.filter((t) => t.group.includes('Performance matrix') && !t.ann.perf)
for (const t of perfFailed) {
  const [, mode, total] = t.title.match(/^Perf (\w+) (\d+)$/) ?? []
  if (mode) perf.push({ mode, total: Number(total), status: t.status, dnf: true })
}
const DNF = { timedOut: '⏱️ did not finish', failed: '❌ failed', interrupted: '⛔ interrupted' }
if (perf.length || perfFailed.length) {
  line('## 2. Performance matrix')
  line()
  line('Each cell is a fresh browser page. **Mount** runs from the click until the first rows are painted and the main thread is free again, and includes the simulated network delay (400 ms for all rows, 150 ms per page). **Heap** is measured after a forced garbage collection. **Scroll** is the built-in 8-second auto-scroll, or less if the list ends first.')
  line()
  line('"Without TanStack Query" is only measured up to 25,000 rows. At 50,000 and above it did not finish within several minutes on the test laptop, so those cells show —.')
  line()
  const totals = [...new Set(perf.map((p) => p.total))].sort((a, b) => a - b)
  const pivot = (title, pick, fmt, note) => {
    line(`### ${title}`)
    line()
    if (note) {
      line(note)
      line()
    }
    line(`| Rows | ${MODES.map((m) => MODE_LABEL[m]).join(' | ')} |`)
    line(`|--:|${MODES.map(() => '--:').join('|')}|`)
    for (const n of totals) {
      const cells = MODES.map((m) => {
        const p = perf.find((x) => x.mode === m && x.total === n)
        if (!p) return '—'
        return p.dnf ? (DNF[p.status] ?? p.status) : fmt(pick(p))
      })
      line(`| ${fmtInt(n)} | ${cells.join(' | ')} |`)
    }
    line()
  }
  pivot('Time to mount', (p) => p.mountMs, fmtMs)
  pivot('Longest main-thread freeze during mount', (p) => p.mountLongestTaskMs, fmtMs)
  pivot('Click → paint (selecting a row)', (p) => p.clickPaintMs, fmtMs)
  pivot('Frame rate while auto-scrolling', (p) => p.scrollAvgFps, (v) => `${v} fps`)
  pivot('Worst single frame while scrolling', (p) => p.scrollWorstFrameMs, fmtMs)
  pivot('DOM nodes in the list after scrolling', (p) => p.domAfterScroll, fmtInt)
  pivot('Rows held in memory after scrolling', (p) => p.rowsAfterScroll, fmtInt)
  pivot('JS heap after scrolling', (p) => p.heapAfterScrollMB, (v) => (v == null ? '–' : `${v} MB`))

  line('### Raw numbers')
  line()
  line('| Tab | Rows | Mount | Mount TBT | Heap before → after mount → after scroll | DOM after mount → scroll | Click → paint | Scroll fps | Worst frame | Janky frames | Scroll TBT | Result |')
  line('|---|--:|--:|--:|--:|--:|--:|--:|--:|--:|--:|:-:|')
  for (const m of MODES)
    for (const n of totals) {
      const p = perf.find((x) => x.mode === m && x.total === n)
      if (!p) continue
      if (p.dnf) {
        line(`| ${MODE_LABEL[m]} | ${fmtInt(n)} | ${DNF[p.status] ?? p.status} | | | | | | | | | ${ICON[p.status] ?? p.status} |`)
        continue
      }
      line(
        `| ${MODE_LABEL[m]} | ${fmtInt(n)} | ${fmtMs(p.mountMs)} | ${fmtMs(p.mountTbtMs)} | ${p.heapBeforeMB} → ${p.heapAfterMountMB} → ${p.heapAfterScrollMB} MB | ${fmtInt(p.domAfterMount)} → ${fmtInt(p.domAfterScroll)} | ${fmtMs(p.clickPaintMs)} | ${p.scrollAvgFps} | ${fmtMs(p.scrollWorstFrameMs)} | ${p.scrollJankyFramePct}% | ${fmtMs(p.scrollTbtMs)} | ${ICON[p.status]} |`,
      )
    }
  line()
}

// ---- 3. Everything else, grouped
const others = tests.filter((t) => t.group !== 'Feature matrix' && !t.group.includes('Performance matrix'))
if (others.length) {
  line('## 3. Page, controls and metrics scenarios')
  line()
  line('| Area | Scenario | Result | Time |')
  line('|---|---|:-:|--:|')
  for (const t of others) line(`| ${t.group} | ${t.title} | ${ICON[t.status] ?? t.status} | ${secs(t.duration)} |`)
  line()
}

// ---- 4. Failures
const failures = tests.filter((t) => !['passed', 'skipped'].includes(t.status))
line('## 4. Failures')
line()
if (!failures.length) line('None.')
for (const t of failures) {
  line(`### ❌ ${t.group} › ${t.title}`)
  line()
  line('```')
  line(strip(t.error).split('\n').slice(0, 12).join('\n'))
  line('```')
  line()
}

line('## How to re-run')
line()
line('```sh')
line('npm run test:e2e        # functional tests + perf matrix (~15 min)')
line('npm run test:quick      # everything except the perf matrix')
line('npm run test:report     # regenerate this file from test-results/results.json')
line('```')

writeFileSync('TEST-MATRIX.md', out.join('\n') + '\n')

// ---- Compact data for the in-app results page (results.html). Bundled at build time.
const cell = (t) => {
  if (!t) return null
  const a = t.ann
  const value = a.domNodes ? `${fmtInt(Number(a.domNodes))} nodes` : a.clickPaintMs ? fmtMs(Number(a.clickPaintMs)) : a.idleFps ? `${a.idleFps} fps` : undefined
  return { status: t.status, value }
}
const data = {
  generatedAt: report.stats.startTime,
  durationMs: Math.round(report.stats.duration),
  browser,
  machine: `${os.cpus()[0]?.model.trim()}, ${Math.round(os.totalmem() / 1e9)} GB RAM`,
  stats: { total: tests.length, passed, failed, skipped: count('skipped') },
  features: [...new Set(feature.map((t) => t.title.replace(/ \[\w+\]$/, '')))].map((f) => ({
    feature: f,
    naive: cell(feature.find((x) => x.title === `${f} [naive]`)),
    query: cell(feature.find((x) => x.title === `${f} [query]`)),
    virtual: cell(feature.find((x) => x.title === `${f} [virtual]`)),
  })),
  perf: perf.map(({ status, dnf, ...rest }) => ({ ...rest, status, dnf: !!dnf })),
  checks: others.map((t) => ({ group: t.group, title: t.title, status: t.status, durationMs: Math.round(t.duration) })),
  failures: failures.map((t) => ({ title: `${t.group} › ${t.title}`, error: strip(t.error).split('\n')[0] })),
}
writeFileSync('src/results/test-results.json', JSON.stringify(data, null, 1) + '\n')
console.log(`TEST-MATRIX.md written: ${tests.length} tests, ${passed} passed, ${failed} failed.`)
